# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ChecksController`.
# Please instead update this file by running `bin/tapioca dsl ChecksController`.

class ChecksController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
