# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `VueController`.
# Please instead update this file by running `bin/tapioca dsl VueController`.

class VueController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
